---
title: "[Publications](https://scholar.google.com/citations?user=f5zdvDAAAAAJ&hl=en&oi=ao)"
output:
  html_document:
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="academicons/css/academicons.min.css"/>

-----

In the following, $^\dagger$ denotes equal contribution.

### 2025
Yan B, Nam Y, Li L, **Deek RA**, Li H, Ma S. Recent advances in deep learning and language models for studying the microbiome. Frontiers in Genetics. 2025. 15, 1494474.

### 2024

Wang T, Kim J, Kumar R, **Deek RA**, Stephenson R, Mayer T, Saraiya B, Ghodoussipour S, Jang T, Golombos D, Packiam V, Ennis R, Hathout L, Jabbour SK, Guler O, Onal C, Deek MP. Landscape and prognostic significance of oncogene drivers in metastatic castration sensitive prostate cancer. Translational Cancer Research. 2024. 13(11), 6235.

Duan, H., Ren J, Wei S, Li C, Wang Z, Li M, Wei Z, Yang Z, Liu Y, Xie Y, Wu S, Hu W, Guo C, Zhang X, Liang L, Yu C, Mou Y, Jiang Y, Lu H, Sugarman E, **Deek RA**, Chen Z, Chen L, Chen Y, Yao M, Liu L, Mou Y, Zhang G. Integrated analyses of Multi-omic data derived from paired primary lung cancer and brain metastasis reveals the metabolic vulnerability as a novel therapeutic target. Genome Medicine. 2024. 16(1), 1-30.

Little A, **Deek RA**, Zhang A, Zhao N, Ling W, Wu MC. Enhanced visualization of microbiome data in repeated measures designs. Frontiers in Genetics. 2024. 15, 1480972.

Sutera P, Kim J, Kumar R, **Deek RA**, Stephenson R, Mayer T, Saraiya B, Ghodoussipour S, Jang T, Golombos D, Packiam V, Ennis R, Hathout L, Jabbour SK, Guler O, Onal C, Tran PT, Deek MP. PIK3/Akt/mTOR pathway alterations in metastatic castration-sensitive prostate cancer. The Prostate. 2024. 1-8.

**Deek RA**, Ma S, Lewis JD, Li H. Statistical and computational methods for integrating microbiome, host genomics, and metabolomics data. eLife. 2024. 13:e88956.

Sutera P$^\dagger$, Deek MP$^\dagger$, **Deek RA**, Guler OC, Hurmuz P, Reyhan M, Rowe S, Radwan N, Dipasquale S, Hrinivich WT, Lowe K, Ren L, Saraiya B, Ennis R, Hathout L, Mayer T, Deweese TL, Song DY, Kiess A, Oymak E, Pienta K, Feng F, Pomper M, Ozyigit G, Tran PT, Onal C, Phillips RM. Prostate-specific membrane antigen PET response associates with metastasis-free survival following stereotactic ablative radiation in oligometastatic prostate cancer. Advances in Radiation Oncology. 2024. 101507.

Deek AJ, **Deek RA**, Clegg DJ, Blackburn C, Holley T, Gotcher JE. To what extent do oral maxillofacial surgery residents suffer from imposter syndrome? Oral Surgery, Oral Medicine, Oral Pathology and Oral Radiology. 2024. 

Khullar K, **Deek RA**, Nelson B, Gaines D, Corrigan KL, LeCompte MC, Deville C, Deek MP, Jabbour SK. Gender and the receipt of the Association of Residents in Radiation Oncology (ARRO) educator of the year award. 2023. Advances in Radiation Oncology: 101305. doi: [10.1016/j.adro.2023.101305](https://doi.org/10.1016/j.adro.2023.101305).

### 2023

Deek AJ, Clegg DJ, **Deek RA**, Blackburn C, Scott CA, Holley T, Gotcher JE. Risk factors for pediatric facial trauma in an Appalachian region: An epidemiologic review at a single institution. 2023. Journal of Oral and Maxillofacial Surgery. doi: [10.1016/j.joms.2023.12.010](https://doi.org/10.1016/j.joms.2023.12.010).

**Deek RA**, Li H. Inference of microbial covariation networks using copula models with mixture margins. Bioinformatics. 2023. 39(7):btad413. doi: [10.1093/bioinformatics/btad413](https://doi.org/10.1093/bioinformatics/btad413).

### 2022

McGinniss JE, Whiteside SA, **Deek RA**, Simon-Soro A, Graham-Wooten J, Oyster M, Brown MD, Cantu E, Diamond JM, Li H, Christie JD, Bushman FD, Collman RG. The lung allograft microbiome associates with pepsin, inflammation, and primary graft dysfunction. American Journal of Respiratory and Critical Care Medicine. 2022. 206(12):1508-21. doi: [10.1164/rccm.202112-2786OC](https://doi.org/10.1164/rccm.202112-2786OC).

Deek MP$^\dagger$, Van der Eecken K$^\dagger$, Sutera P, **Deek RA**, Fonteyne V, Mendes AA, Decaestecker K, Kiess AP, Lumen N, Phillips R, De Bruycker A, Mishra M, Rana Z, Molitoris J, Lambert B, Delrue L, Wang H, Lowe K, Verbeke S, Van Dorpe J, Bultijnck R, Villeirs G, De Man K, Ameye F, Song DY, DeWeese T, Paller CJ, Feng FY, Wyatt A, Pienta KJ, Diehn M, Bentzen SM, Joniau S, Vanhaverbeke F, De Meerleer G, Antonarakis ES, Lotan TL, Berlin A, Siva S, Ost P, Tran PT. Long-term outcomes and genetic predictors of response to metastasis-directed therapy versus observation in oligometastatic prostate cancer: analysis of STOMP and ORIOLE trials. Journal of clinical oncology. 2022. 40(29):3377-82. doi: [10.1200/JCO.22.00644](https://doi.org/10.1200/JCO.22.00644).

Wei S, Yin D, Yu S, Lin X, Savani MR, Du K, Ku Y, Wu D, Li S, Liu H, Tian M, Chen Y, Bowie M, Hariharan S, Waitkus M, Keir S, Sugarman E, **Deek RA**, Labrie M, Khasraw M, Lu Y, Mills G, Herlyn H, Wu K, Liu L, Wei Z, Flaherty K, Abdullah K, Zhang G, and Ashley D. Antitumor activity of a mitochondrial-targeted HSP90 inhibitor in gliomas. Clinical Cancer Research. 2022. 28(10):2180-95. doi: [10.1158/1078-0432.ccr-21-0833](https://doi.org/10.1158/1078-0432.ccr-21-0833).

### 2021

**Deek RA**, Li H. A zero-inflated latent dirichlet allocation model for microbiome studies. Frontiers in Genetics. 2021. 11:602594. doi: [10.3389/fgene.2020.602594](https://doi.org/10.3389/fgene.2020.602594).

### 2019

**Deek RA**$^\dagger$, Nasser J$^\dagger$, Ghanem A$^\dagger$, Mardelli M$^\dagger$, Khazen G, Salloum AK, Abchee A, Ghassibe-Sabbagh M, Zalloua P. Genome-wide association analysis of HDL-C in a Lebanese cohort. Plos one. 2019. 14(6):e0218443. doi: [10.1371/journal.pone.0218443](https://doi.org/10.1371/journal.pone.0218443).

### 2018

Chen J$^\dagger$, King E$^\dagger$, **Deek RA**$^\dagger$, Wei Z, Yu Y, Grill D, Ballman K. An omnibus test for differential distribution analysis of microbiome sequencing data. Bioinformatics. 2018. 34(4):643-51. doi: [10.1093/bioinformatics/btx650](https://doi.org/10.1093/bioinformatics/btx650).

### 2015

Deek, R. (2015). Lessons From Nature: Defensive Designs for the Built Environment. In 5th International Conference on Building Resilience.